### ISSUE TITLE
PHP SDK: API error message truncated when sending a null value for a CDA

### ISSUE THREAD

**Issue by choran** [intercom/intercom-php#237]
Running this in the PHP SDK

```php
$client->leads->create([
  "email"=>"user@example.com",
  "custom_attributes"=>[
    "test"=>null
    ],
]);
```
outputs this

```
root@fc8f8a8a0dd5:/intercom# php test.php

PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.intercom.io/contacts` resulted in a `400 Bad Request` response:
{"type":"error.list","request_id":"aq389072mea8j3m80530","errors":[{"code":"parameter_invalid","message":"Value:  not of (truncated...)
' in /intercom/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /intercom/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /intercom/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /intercom/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /intercom/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /intercom/vendor/guzzlehttp/promises/src/P 
in /intercom/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111
```
Looks like the issue here is the `Value:  not of (truncated...)` in the PHP exception. Is it possible to surface the full error message to the user? 

Compare to the ruby SDK which contains the actual error message returned by our API

```
/Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/request.rb:143:in `raise_application_errors_on_failure': Value:  not of type Numeric, String or Boolean (Intercom::BadRequestError)
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/request.rb:94:in `parse_body'
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/request.rb:70:in `block in execute'
	from /Users/Micheal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/request.rb:65:in `execute'
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/client.rb:111:in `execute_request'
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/client.rb:92:in `post'
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/api_operations/save.rb:26:in `save'
	from /Users/Micheal/.rvm/gems/ruby-2.3.3@global/gems/intercom-3.5.9/lib/intercom/api_operations/save.rb:18:in `create'
	from ruby.rb:11:in `<main>'
```

**Comment by kahuwi** [comment]
you will need to use try(){}catch(e)();  when you call intercom.
when the catch returns it will have what happened in e.

**Comment by choran** [comment]
@kahuwi Thanks for that, I wasnt aware of that.
If you get a chance to submit any kind of PR I can review it as well and update/approve as needed.
No hassle if you dont, I will take a look at this when I get a chance myself.
thanks again

**Comment by kahuwi** [comment]
take a look at:  https://github.com/intercom/intercom-php/issues/185

**Comment by choran** [comment]
Will do, there is quite a discussion on the issue so will read through it to get more context.
There does seems to be relevant discussion in that issue so it will be helpful
Thanks 
Cathal

**Comment by GabrielAnca** [comment]
As stated in my previous message, in both versions 3 and 4 of this library the full error message is included in the exception that is thrown, so the library users have all they need to check the complete error message and take appropriate action. The exception message is truncated only if the exception is not catched.

I'll be closing this issue now, feel free to reopen it if you think this is still an issue. 😃
